control:

  steering_pid:
    Kp: 0.07
    Ki: 0.0
    Kd: 0.06
    Kf: 0.09

  max_steering_change: 0.22
  base_throttle: 0.12
  target_speed_kph: 40
  speed_pid:
    Kp: 0.02
    Ki: 0.0
    Kd: 0.01
