etk800:
  camera_front:
    name: "camera_front"
    enabled: true
    requested_update_time: 0.05
    pos: [ 0.02461, -0.4155, 1.36 ]
    dir: [ 0.001929, -1, -0.00476 ]
    up: [ 0.00476, -0.0001314, 1 ]
    resolution: [ 1920, 1080 ] # 1080p for HD mapping
    field_of_view_y: 70
    near_far_planes: [ 0.05, 200 ]
    is_using_shared_memory: false
    is_render_colours: true
    is_render_annotations: false
    is_render_depth: true
    is_depth_inverted: false
    is_visualised: true
    is_streaming: true
    integer_depth: true
    postprocess_depth: false
    is_static: false
    is_dir_world_space: false

  lidar_top:
    name: "lidar_top"
    enabled: true
    requested_update_time: 0.05
    pos: [ 0.002427, 0.8515, 1.554 ]
    dir: [ -0.0008008, -1, 0.003882 ]
    up: [ -0.003876, -0.007295, 1 ]
    vertical_angle: 26.9
    vertical_resolution: 80
    horizontal_angle: 360
    frequency: 20
    max_distance: 120
    density: 1
    is_360_mode: true
    is_rotate_mode: false
    is_using_shared_memory: true
    is_visualised: false
    is_streaming: true
    is_annotated: false
    is_static: false
    is_dir_world_space: false

  radar_front:
    name: "radar_front"
    enabled: true
    requested_update_time: 0.05
    pos: [ 0, -2.5, 0.5 ]
    dir: [ 0, -1, 0 ]
    up: [ 0, 0, 1 ]
    size: [ 200, 200 ]
    near_far_planes: [ 0.1, 200 ]
    field_of_view_y: 18
    range_min: 0.5
    range_max: 150.0
    vel_min: -40
    vel_max: 40
    range_bins: 128
    azimuth_bins: 64
    vel_bins: 32
    half_angle_deg: 9

  radar_rear_left:
    name: "radar_rear_left"
    enabled: false
    requested_update_time: 0.05
    pos: [ 0.808, 2.305, 0.673 ]
    dir: [ 0.2382, 0.9709, 0.02624 ]
    up: [ -0.2821, 0.9592, 0.01801 ]
    size: [ 200, 200 ]
    near_far_planes: [ 0.1, 200 ]
    field_of_view_y: 18
    range_min: 0.5
    range_max: 150.0
    vel_min: -40
    vel_max: 40
    range_bins: 128
    azimuth_bins: 64
    vel_bins: 32
    half_angle_deg: 9

  radar_rear_right:
    name: "radar_rear_right"
    enabled: false
    requested_update_time: 0.05
    pos: [ -0.7882, 2.332, 0.673 ]
    dir: [ -0.2416, 0.9694, 0.04251 ]
    up: [ 0.04892, 0.02059, 0.9986 ]
    size: [ 100, 100 ]
    near_far_planes: [ 0.1, 30 ]
    field_of_view_y: 60
    range_min: 0.5
    range_max: 150.0
    vel_min: -20
    vel_max: 20
    range_bins: 64
    azimuth_bins: 32
    vel_bins: 16
    half_angle_deg: 30

  gps_front:
    name: "gps_front"
    enabled: true
    gfx_update_time: 0.0
    physics_update_time: 0.05
    pos: [ -0.006261, -2.187, 0.3567 ]
    ref_lat: 51.5074 # Berlin coordinates (example)
    ref_lon: 13.1856
    is_send_immediately: false
    is_visualised: false
    is_snapping_desired: false
    is_force_inside_triangle: false
    is_dir_world_space: false

  gps_rear:
    name: "gps_rear"
    enabled: true
    gfx_update_time: 0.0
    physics_update_time: 0.05
    pos: [ -0.003197, 2.382, 0.3765 ]
    ref_lat: 51.5074 # Berlin coordinates (example)
    ref_lon: 13.1856
    is_send_immediately: false
    is_visualised: false
    is_snapping_desired: false
    is_force_inside_triangle: false
    is_dir_world_space: false

  imu_1:
    name: "imu_1"
    enabled: true
    gfx_update_time: 0.0
    physics_update_time: 0.01
    pos: [ -0.006876, 0.03767, 0.5556 ]
    smoother_strength: 1.0
    is_send_immediately: false
    is_using_gravity: false
    is_allow_wheel_nodes: false
    is_visualised: false
    is_snapping_desired: false
    is_force_inside_triangle: false
    is_dir_world_space: false

  powertrain_info:
    name: "powertrain_info"
    enabled: true
    gfx_update_time: 0.1
    physics_update_time: 0.015
    is_send_immediately: false

q8_andronisk:
  camera_front:
    name: "camera_front"
    enabled: true
    requested_update_time: 0.01
    is_using_shared_memory: true
    pos: [ 0, -0.58, 1.466 ]
    dir: [ 0, -1, 0 ]
    field_of_view_y: 70
    near_far_planes: [ 0.2, 200.0 ]
    resolution: [ 1920, 1080 ]
    is_streaming: true
    is_render_colours: true
    is_render_depth: true

  lidar_top:
    name: "lidar_top"
    enabled: true
    requested_update_time: 0.01
    is_using_shared_memory: true
    is_rotate_mode: false
    horizontal_angle: 170
    vertical_angle: 30
    vertical_resolution: 64
    density: 7
    frequency: 15
    max_distance: 100
    pos: [ 0, -0.232, 1.638 ]
    dir: [ 0, -1, 0 ]
    is_visualised: false

  radar_front:
    name: "radar_front"
    enabled: true
    requested_update_time: 0.05
    pos: [ 0, -2.345, 0.610 ]
    dir: [ 0, -1, 0 ]
    up: [ 0, 0, 1 ]
    size: [ 200, 200 ]
    near_far_planes: [ 0.1, 200 ]
    field_of_view_y: 18
    range_min: 0.5
    range_max: 150.0
    vel_min: -40
    vel_max: 40
    range_bins: 128
    azimuth_bins: 64
    vel_bins: 32
    half_angle_deg: 9

  radar_rear_left:
    name: "radar_rear_left"
    enabled: false
    requested_update_time: 0.05
    pos: [ 0.808, 2.305, 0.673 ]
    dir: [ 0.2382, 0.9709, 0.02624 ]
    up: [ -0.2821, 0.9592, 0.01801 ]
    size: [ 200, 200 ]
    near_far_planes: [ 0.1, 200 ]
    field_of_view_y: 18
    range_min: 0.5
    range_max: 150.0
    vel_min: -40
    vel_max: 40
    range_bins: 128
    azimuth_bins: 64
    vel_bins: 32
    half_angle_deg: 9

  radar_rear_right:
    name: "radar_rear_right"
    enabled: false
    requested_update_time: 0.05
    pos: [ -0.7882, 2.332, 0.673 ]
    dir: [ -0.2416, 0.9694, 0.04251 ]
    up: [ 0.04892, 0.02059, 0.9986 ]
    size: [ 100, 100 ]
    near_far_planes: [ 0.1, 30 ]
    field_of_view_y: 60
    range_min: 0.5
    range_max: 150.0
    vel_min: -20
    vel_max: 20
    range_bins: 64
    azimuth_bins: 32
    vel_bins: 16
    half_angle_deg: 30

  gps_front:
    name: "gps_front"
    enabled: true
    gfx_update_time: 0.0
    physics_update_time: 0.05
    pos: [ -0.006261, -2.187, 0.3567 ]
    ref_lat: 51.5074 # Berlin coordinates (example)
    ref_lon: 13.1856
    is_send_immediately: false
    is_visualised: false
    is_snapping_desired: false
    is_force_inside_triangle: false
    is_dir_world_space: false

  gps_rear:
    name: "gps_rear"
    enabled: true
    gfx_update_time: 0.0
    physics_update_time: 0.05
    pos: [ -0.003197, 2.382, 0.3765 ]
    ref_lat: 51.5074 # Berlin coordinates (example)
    ref_lon: 13.1856
    is_send_immediately: false
    is_visualised: false
    is_snapping_desired: false
    is_force_inside_triangle: false
    is_dir_world_space: false

  imu_1:
    name: "imu_1"
    enabled: true
    gfx_update_time: 0.01
    physics_update_time: 0.01
    pos: [ 0, -0.03256, 0.4972 ]
    dir: [ 0, -1, 0 ]
    up: [ 0, 0, 1 ]
    smoother_strength: 1.0
    is_send_immediately: false
    is_using_gravity: false
    is_allow_wheel_nodes: true
    is_visualised: false
    is_snapping_desired: false
    is_force_inside_triangle: false
    is_dir_world_space: false

  powertrain_info:
    name: "powertrain_info"
    enabled: true
    gfx_update_time: 0.1
    physics_update_time: 0.015
    is_send_immediately: false
